In [6]:
import numpy as np

import pandas as pd

from pandas import Series, DataFrame

import matplotlib.pyplot as plt

%matplotlib inline

twibit = pd.read_csv('/content/finaldata2.csv')

In [8]:
x = twibit[['Close','Volume','Polarity']]

In [9]:
y = twibit.target

**Linear regression**

In [10]:
# importing linear regression
from sklearn.linear_model import LinearRegression

lreg = LinearRegression()

In [12]:
# for cross validation

from sklearn.model_selection import train_test_split


x_train, x_cv, y_train, y_cv = train_test_split(x,y, test_size =0.3)

In [13]:
# training a linear regression model on train

lreg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
# predicting on cv

pred_cv = lreg.predict(x_cv)
pred

array([0.57829528, 0.57829528, 0.57829528, ..., 0.57829528, 0.57829528,
       0.57829528])

In [15]:
# calculating mse

mse = np.mean((pred_cv - y_cv)**2)

mse



8582.470465270468

In [16]:

# evaluation using r-square

lreg.score(x_cv,y_cv)

0.004304340732754763

**Ridge Regression**

In [26]:
from sklearn.linear_model import Ridge

## training the model

ridgeReg = Ridge(alpha=0.05, normalize=True)

ridgeReg.fit(x_train,y_train)

pred = ridgeReg.predict(x_cv)

pred

array([ 0.44359755,  1.1142751 ,  1.04983397, ..., -0.82335563,
        1.33444067,  1.2136299 ])

In [27]:
#calculating mse

mse = np.mean((pred_cv - y_cv)**2)

mse 

8588.593921805548

In [28]:
## calculating score 
ridgeReg.score(x_cv,y_cv)

0.0040332049382121316

**Lasso regression**

In [20]:
from sklearn.linear_model import Lasso

lassoReg = Lasso(alpha=0.3, normalize=True)

lassoReg.fit(x_train,y_train)

pred = lassoReg.predict(x_cv)

pred

array([0.57829528, 0.57829528, 0.57829528, ..., 0.57829528, 0.57829528,
       0.57829528])

In [18]:
# calculating mse

mse = np.mean((pred_cv - y_cv)**2)
mse

8582.470465270468

In [19]:
lassoReg.score(x_cv,y_cv)

-0.0011054831756720507

**Elastic Net Regression**

In [23]:
from sklearn.linear_model import ElasticNet

ENreg = ElasticNet(alpha=1, l1_ratio=0.5, normalize=False)

ENreg.fit(x_train,y_train)

pred_cv = ENreg.predict(x_cv)
pred_cv

array([0.6973733 , 0.64234325, 0.62703546, ..., 0.63162651, 0.7049507 ,
       0.73251166])

In [24]:
#calculating mse

mse = np.mean((pred_cv - y_cv)**2)

mse 


8588.593921805548

In [25]:
ENreg.score(x_cv,y_cv)

0.0035939276743744974